/**
 * `stitchkit/testing` — integration helpers that preserve the production
 * generated-client and Fetch-handler pipelines without opening a TCP port.
 */

export * from '../testing/handler-clients';
export {
  type ManagedResourceConformanceConfig,
  type ManagedResourceConformanceControls,
  ManagedResourceConformanceError,
  type ManagedResourceConformanceFactoryInput,
  type ManagedResourceConformanceFixture,
  type ManagedResourceConformancePhase,
  ManagedResourceConformancePhaseSchema,
  type ManagedResourceConformanceScenario,
  type ManagedResourceConformanceScenarioId,
  ManagedResourceConformanceScenarioIdSchema,
  ManagedResourceConformanceScenarioSchema,
  type ManagedResourceConformanceTraceEntry,
  ManagedResourceConformanceTraceEntrySchema,
  type ManagedResourceConformanceTraceOutcome,
  ManagedResourceConformanceTraceOutcomeSchema,
  runManagedResourceConformance,
} from '../testing/managed-resource-conformance';
export {
  type CreateRealtimeProbeDriverConfig,
  createRealtimeProbeDriver,
  type DefineRealtimeProbeConfig,
  defineRealtimeProbe,
  type RealtimeProbeAdapter,
  type RealtimeProbeFixture,
  type RealtimeProbeScenario,
} from '../testing/realtime-probe';
export {
  assertSurfaceDiscovery,
  type ConformanceTransport,
  type RealtimeDisconnectObservation,
  RealtimeDisconnectObservationSchema,
  type RealtimeRejectionObservation,
  RealtimeRejectionObservationSchema,
  type RunSurfaceProbesConfig,
  runSurfaceProbes,
  type SurfaceDiscoveryObservation,
  type SurfaceProbe,
  type SurfaceProbeDriver,
  type SurfaceRealtimeDiscoveryObservation,
  type SurfaceToolDiscoveryObservation,
  type TransportObservation,
  TransportObservationSchema,
} from '../testing/surface-conformance';
export {
  assertSurfaceManifestSnapshot,
  buildSurfaceManifest,
  type IncompatibleSchemaPolicy,
  type McpSchemaValidationConfig,
  SURFACE_MANIFEST_VERSION,
  type SurfaceAgentProjection,
  type SurfaceManifest,
  type SurfaceManifestConfig,
  type SurfaceManifestExtension,
  SurfaceManifestExtensionSchema,
  type SurfaceManifestOperation,
  type SurfaceManifestOperationMcp,
  SurfaceManifestOperationMcpSchema,
  SurfaceManifestOperationSchema,
  type SurfaceManifestOperationToolView,
  SurfaceManifestOperationToolViewSchema,
  type SurfaceManifestRealtimeEvent,
  SurfaceManifestRealtimeEventSchema,
  SurfaceManifestSchema,
  type SurfaceManifestTool,
  SurfaceManifestToolSchema,
  type SurfaceManifestToolSurface,
  SurfaceManifestToolSurfaceSchema,
  type SurfaceMcpPreparation,
  SurfaceRealtimeSchemaPairSchema,
  type SurfaceRuntimeToolDefinition,
  SurfaceSchemaDigestsSchema,
  type SurfaceToolDefinition,
  type SurfaceToolExtension,
  serializeSurfaceValue,
} from '../testing/surface-manifest';
